language: python
virtualenv:
  system_site_packages: true
sudo: required
services:
  - postgresql
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-m2crypto python-dateutil python-openssl
  - sudo apt-get install -y libxmlsec1 xmlsec1 libxmlsec1-openssl libxmlsec1-dev
before_script:
  - wget https://github.com/GENI-NSF/geni-tools/archive/v2.10.tar.gz -O /tmp/geni-tools.tar.gz
  - tar -xf /tmp/geni-tools.tar.gz -C /tmp
  - export PYTHONPATH=$PYTHONPATH:/tmp/geni-tools-2.10/src
  - psql -c 'create database geni;' -U postgres
  - psql -c "create user ch with password 'secret';" -U postgres
  - psql -c 'grant all on database geni to ch;' -U postgres
  - echo 'localhost:*:geni:ch:secret' > ~/.pgpass
  - chmod 0600 ~/.pgpass
script:
  - test/travis-build
